name = "RayleighSetup"
uuid = "75b79246-00b7-4463-9512-3f095bd1a3df"
authors = ["haralg <haralbbj@stud.ntnu.no>"]
version = "0.1.0"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"

[compat]
FFTW = "1.7.1"
julia = "1.9.3"
